syntax = "proto3";

package bot.v1;

option go_package = "github.com/AndreeJait/zora-code-rpc/generated/go/bot/v1;botv1";
option java_multiple_files = true;
option csharp_namespace = "ZoraCode.Rpc.Bot.V1";

message BotContact {
  string id = 1;
  string number = 2;
  string name = 3;
  string push_name = 4;
  string short_name = 5;
  bool is_group = 6;
}

message SearchContactsRequest {
  string query = 1;
  int32 limit = 2;
}

message SearchContactsResponse {
  repeated BotContact contacts = 1;
}

service ContactService {
  rpc SearchContacts(SearchContactsRequest) returns (SearchContactsResponse);
}
