syntax = "proto3";

package bot.v1;

option go_package = "github.com/AndreeJait/zora-code-rpc/generated/go/bot/v1;botv1";
option java_multiple_files = true;
option csharp_namespace = "ZoraCode.Rpc.Bot.V1";

import "common/v1/types.proto";
import "google/protobuf/timestamp.proto";

message BotIncomingMedia {
  string id = 1;
  string message_id = 2;
  string chat_id = 3;
  string participant_id = 4;
  string object_key = 5;
  string mimetype = 6;
  int32 size_bytes = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp expires_at = 9;
}

message ListIncomingMediaRequest {
  string chat_id = 1;
  string participant_id = 2;
}

message ListIncomingMediaResponse {
  repeated BotIncomingMedia media = 1;
}

message GetIncomingMediaRequest {
  string id = 1;
}

message DeleteIncomingMediaRequest {
  string id = 1;
}

service MediaService {
  rpc ListIncomingMedia(ListIncomingMediaRequest) returns (ListIncomingMediaResponse);
  rpc GetIncomingMedia(GetIncomingMediaRequest) returns (BotIncomingMedia);
  rpc DeleteIncomingMedia(DeleteIncomingMediaRequest) returns (common.v1.DeleteResponse);
}
